@extends('layouts.app')
@section('title', $requisition->exists ? 'Edit Requirement' : 'New Requirement')
@section('actions')
    <a href="{{ $requisition->exists ? route('selection.show', $requisition) : route('selection.index') }}" class="inline-flex items-center gap-1 rounded-md border border-slate-300 text-slate-700 font-semibold text-sm px-3 py-1.5 hover:bg-slate-100 transition">← Cancel</a>
@endsection
@section('content')

@php
    // Contacts per company, used to filter the contact dropdown when a company is picked.
    $contactMap = $principals->mapWithKeys(fn ($p) => [
        (string) $p->id => $p->contacts->map(fn ($c) => [
            'id' => $c->id,
            'name' => $c->name.($c->designation ? ' — '.$c->designation : ''),
        ])->values(),
    ]);
    $selectedPrincipal = old('principal_id', $requisition->principal_id);
    $selectedContact = old('principal_contact_id', $requisition->principal_contact_id);
@endphp

<form method="POST" action="{{ $requisition->exists ? route('selection.update', $requisition) : route('selection.store') }}"
      class="bg-white rounded-xl shadow p-6 md:p-8">
    @csrf
    @if ($requisition->exists) @method('PUT') @endif

    <h3 class="font-semibold text-navy-800 mb-5 pb-4 border-b border-slate-100">{{ $requisition->exists ? 'Edit requirement' : 'New requirement' }}</h3>

    <div class="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
        <div>
            <label class="block text-[11px] uppercase tracking-wide text-slate-400 mb-1">Company *</label>
            <select name="principal_id" id="reqCompany" required data-placeholder="Select company…" class="w-full border border-slate-300 rounded-md px-3 py-2">
                <option value="">Select company…</option>
                @foreach ($principals as $p)<option value="{{ $p->id }}" @selected($selectedPrincipal==$p->id)>{{ $p->name }}</option>@endforeach
            </select>
        </div>
        <div>
            <label class="block text-[11px] uppercase tracking-wide text-slate-400 mb-1">Company contact</label>
            <select name="principal_contact_id" id="reqContact" class="w-full border border-slate-300 rounded-md px-3 py-2 no-enhance">
                <option value="">Select a company first…</option>
            </select>
            <div class="text-[10px] text-slate-400 mt-1">Contacts come from the selected company's profile.</div>
        </div>
        <div>
            <label class="block text-[11px] uppercase tracking-wide text-slate-400 mb-1">Reference</label>
            <input type="text" value="{{ $requisition->exists ? $requisition->reference : '' }}" readonly
                   placeholder="Generated automatically on save"
                   class="w-full border border-slate-200 bg-slate-50 text-slate-500 rounded-md px-3 py-2 cursor-not-allowed">
            <div class="text-[10px] text-slate-400 mt-1">The reference number is generated by the system.</div>
        </div>
        <div>
            <label class="block text-[11px] uppercase tracking-wide text-slate-400 mb-1">Requirement date</label>
            <input type="date" name="requirement_date" value="{{ old('requirement_date', optional($requisition->requirement_date)->toDateString()) }}" class="w-full border border-slate-300 rounded-md px-3 py-2">
        </div>
        @php $deadlineLocked = $requisition->exists && $requisition->deadlinePassed() && ! auth()->user()->hasRole('Super Admin'); @endphp
        <div>
            <label class="block text-[11px] uppercase tracking-wide text-slate-400 mb-1">Deadline</label>
            <input type="date" name="deadline" @readonly($deadlineLocked) value="{{ old('deadline', optional($requisition->deadline)->toDateString()) }}"
                   class="w-full border {{ $deadlineLocked ? 'border-slate-200 bg-slate-50 text-slate-500 cursor-not-allowed' : 'border-slate-300' }} rounded-md px-3 py-2">
            @if ($deadlineLocked)
                <div class="text-[10px] text-amber-600 mt-1">Deadline has passed — only a Super Admin can extend it.</div>
            @else
                <div class="text-[10px] text-slate-400 mt-1">All positions must be added and crew placed onboard before this date. After it passes, no new position/crew can be added.</div>
            @endif
        </div>
        <div class="md:col-span-2">
            <label class="block text-[11px] uppercase tracking-wide text-slate-400 mb-1">Notes</label>
            <textarea name="notes" rows="3" class="w-full border border-slate-300 rounded-md px-3 py-2">{{ old('notes', $requisition->notes) }}</textarea>
        </div>
    </div>

    <div class="flex gap-2 mt-6 pt-5 border-t border-slate-100">
        <button class="bg-[#1F3864] text-white font-semibold px-6 py-2 rounded-md hover:bg-[#2E74B5] transition">{{ $requisition->exists ? 'Save changes' : 'Create requirement' }}</button>
        <a href="{{ $requisition->exists ? route('selection.show', $requisition) : route('selection.index') }}" class="px-6 py-2 rounded-md border border-slate-300 text-slate-700 font-semibold hover:bg-slate-100">Cancel</a>
    </div>
</form>

<script>
(function () {
    var CONTACTS = @json($contactMap);
    var preselect = @json((string) ($selectedContact ?? ''));
    var company = document.getElementById('reqCompany');
    var contact = document.getElementById('reqContact');
    if (!company || !contact) return;

    function fill(keepValue) {
        var list = CONTACTS[company.value] || [];
        contact.innerHTML = '';
        var first = document.createElement('option');
        first.value = '';
        first.textContent = company.value ? (list.length ? 'Select contact…' : 'No contacts on this company') : 'Select a company first…';
        contact.appendChild(first);
        list.forEach(function (c) {
            var o = document.createElement('option');
            o.value = c.id; o.textContent = c.name;
            if (keepValue && String(c.id) === String(keepValue)) o.selected = true;
            contact.appendChild(o);
        });
    }

    fill(preselect);
    company.addEventListener('change', function () { fill(null); });
})();
</script>
@endsection
